Minor Improvements:
apache/commons-bcel pull request #76
Opened 2021-01-04 19:29 UTC by arturobernalg

* Add final to variable
* Use 'Map.computeIfAbsent'

2021-02-04 16:48 UTC, garydgregory commented
@arturobernalg 
May you please rebase?

2021-02-05 05:19 UTC, arturobernalg commented
> @arturobernalg
> May you please rebase?

HI @garydgregory 

Done

2021-02-05 14:55 UTC, garydgregory requested changes

2021-02-05 14:55 UTC, garydgregory commented on src/main/java/org/apache/bcel/classfile/Utility.java
> +        if ((typeParams.length() == 0) && (index == signature.length())) {
-1: Don't in-line `isEmpty()` calls.

2021-02-05 14:55 UTC, garydgregory commented on src/main/java/org/apache/bcel/classfile/Utility.java
> +                    int CONSUMER_CHARS = bracketIndex + 1; // Shadows global var
-1: don't upper case local vars.

2021-03-07 19:46 UTC, arturobernalg reviewed
Changed

2021-03-19 20:18 UTC, closed without merging